"use strict";

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const state = {persona: localStorage.getItem("gridbrief.persona") || "general", hours: 24, cache: new Map(), inFlight: new Map(), edition: null, history: []};

// The only route from API/local data to a DOM text node. Objects become readable text.
function safeText(value, fallback = "Unavailable") {
  if (value === null || value === undefined || value === "") return fallback;
  if (value instanceof Error) return value.message || fallback;
  if (typeof value === "object") {
    if (typeof value.detail === "string") return value.detail;
    if (Array.isArray(value.detail)) return value.detail.map(v => safeText(v, "")).filter(Boolean).join("; ") || fallback;
    try { return JSON.stringify(value, null, 2); } catch { return fallback; }
  }
  const result = String(value);
  return result === "[object Object]" ? fallback : result;
}
function text(element, value, fallback) { element.textContent = safeText(value, fallback); return element; }
function el(tag, className, value) { const node = document.createElement(tag); if (className) node.className = className; if (value !== undefined) text(node, value); return node; }
function fmt(value, unit = "") { return Number.isFinite(Number(value)) ? `${new Intl.NumberFormat("en-US", {maximumFractionDigits: unit === "$/MWh" ? 2 : 0}).format(Number(value))} ${unit}`.trim() : "No data"; }
function marketTime(value) { if (!value) return "Time unavailable"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? "Time unavailable" : new Intl.DateTimeFormat("en-US", {timeZone:"America/Chicago", month:"short", day:"numeric", hour:"numeric", minute:"2-digit", timeZoneName:"short"}).format(date); }
function clear(node) { node.replaceChildren(); }

async function api(path, options = {}) {
  const key = `${options.method || "GET"}:${path}:${options.body || ""}`;
  if (!options.method && state.cache.has(key)) return state.cache.get(key);
  if (state.inFlight.has(key)) return state.inFlight.get(key);
  const request = fetch(path, {...options, headers:{"Content-Type":"application/json", ...(options.headers || {})}}).then(async response => {
    const type = response.headers.get("content-type") || "";
    const body = type.includes("json") ? await response.json() : await response.text();
    if (!response.ok) throw new Error(safeText(body, `Request failed (${response.status})`));
    if (!options.method) state.cache.set(key, body);
    return body;
  }).catch(error => { throw new Error(safeText(error, "GridBrief could not load this data.")); }).finally(() => state.inFlight.delete(key));
  state.inFlight.set(key, request); return request;
}

function errorState(container, error) { clear(container); const box = el("div", "empty"); text(box, safeText(error, "This data is temporarily unavailable.")); container.append(box); }
function metricCard(label, summary, unit) { const card=el("article","kpi"); card.append(el("div","metric-label",label),el("div","metric-value",fmt(summary?.current,unit)),el("div","metric-meta",summary?.coverage ? `${safeText(summary.coverage)} observations · avg ${fmt(summary.average,unit)}` : "No observations in this window")); return card; }
function drawChart(svg, points, label) {
  clear(svg); svg.setAttribute("viewBox","0 0 600 160"); svg.setAttribute("aria-label", safeText(label,"Time series"));
  const values=(points || []).map(p=>Number(p.value)).filter(Number.isFinite); if(values.length<2){svg.append(text(document.createElementNS("http://www.w3.org/2000/svg","text"),"Not enough data"));return;}
  const min=Math.min(...values),max=Math.max(...values),span=max-min||1;
  const path=(points||[]).map((p,i)=>`${i?"L":"M"} ${(i/(points.length-1))*600} ${145-((Number(p.value)-min)/span)*125}`).join(" ");
  const axis=document.createElementNS("http://www.w3.org/2000/svg","line"); axis.setAttribute("class","axis"); axis.setAttribute("x1","0");axis.setAttribute("y1","145");axis.setAttribute("x2","600");axis.setAttribute("y2","145");
  const line=document.createElementNS("http://www.w3.org/2000/svg","path");line.setAttribute("class","line");line.setAttribute("d",path);svg.append(axis,line);
  points.forEach((p,i)=>{ if(i%Math.max(1,Math.floor(points.length/20))) return; const c=document.createElementNS("http://www.w3.org/2000/svg","circle");c.setAttribute("cx",String((i/(points.length-1))*600));c.setAttribute("cy",String(145-((Number(p.value)-min)/span)*125));c.setAttribute("r","7");c.setAttribute("fill","transparent");c.setAttribute("tabindex","0");c.setAttribute("aria-label",`${marketTime(p.ts)}, ${fmt(p.value,p.unit)}`);svg.append(c);});
}

async function loadStatus(){try{const [status,config]=await Promise.all([api("/api/status"),api("/api/config")]);const healthy=(status.sources||[]).filter(s=>s.status==="success");text($("#fresh-status"),healthy.length?"Systems reporting":"Partial coverage");const latest=(status.sources||[]).map(s=>s.window_end||s.last_success_at).filter(Boolean).sort().at(-1);text($("#data-as-of"),`Data as of ${marketTime(latest)}`);text($("#source-health"),`${healthy.length}/${(status.sources||[]).length} sources healthy · ${safeText(config.iso,"ERCOT")}`);}catch(e){text($("#fresh-status"),"Status unavailable");text($("#source-health"),safeText(e));}}
function latestPoint(points){return points?.length?points[points.length-1]:null}
function buildTicker(data){const labels={system_load:"System load",spp_rt:"RT price",spp_da:"DA price",outages:"Outages",fuel_mix_wind:"Wind",fuel_mix_solar:"Solar"};const items=[];Object.entries(labels).forEach(([key,label])=>{const p=latestPoint(data.metrics?.[key]);if(p)items.push(`${label}  ${fmt(p.value,p.unit)}`)});const track=$("#ticker-track");clear(track);const values=items.length?items:["Market data temporarily unavailable"];[...values,...values].forEach(v=>{const span=el("span");const parts=v.split("  ");span.append(el("b","",parts[0]),document.createTextNode("  ·  "),el("i","",parts[1]||""));track.append(span)});}

async function loadWindow(){const buttons=$$("[data-hours]");buttons.forEach(b=>b.disabled=true);try{const [metrics,intel]=await Promise.all([api(`/api/metrics?hours=${state.hours}`),api(`/api/intelligence?hours=${state.hours}`)]);state.intelligence=intel;buildTicker(metrics);renderPulse(metrics);renderIntelligence(intel);renderFuel(intel.fuel_mix||{});renderReliability(intel);text($("#coverage-pill"),`Window ${state.hours===168?"7d":state.hours+"h"}`);}catch(e){[$("#pulse"),$("#role-kpis"),$("#fuel-grid"),$("#reliability"),$("#market")].forEach(n=>errorState(n,e));}finally{buttons.forEach(b=>b.disabled=false)}}
function renderPulse(data){const node=$("#pulse");clear(node);const load=data.metrics?.system_load||[];const current=latestPoint(load);const main=el("article","panel pulse-main");main.append(el("div","metric-label","Current system load"),el("div","metric-value",fmt(current?.value,current?.unit||"MW")));const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("class","chart");drawChart(svg,load,"ERCOT system load");main.append(svg,el("div","metric-meta",`Range ${fmt(Math.min(...load.map(p=>p.value)),"MW")}–${fmt(Math.max(...load.map(p=>p.value)),"MW")} · ${marketTime(current?.ts)}`));node.append(main);[["RT price","spp_rt","$/MWh"],["Day-ahead","spp_da","$/MWh"],["Wind","fuel_mix_wind","MW"]].forEach(([l,k,u])=>node.append(metricCard(l,{current:latestPoint(data.metrics?.[k])?.value,coverage:data.metrics?.[k]?.length},u)));}
function renderIntelligence(intel){const node=$("#role-kpis");clear(node);const sets={general:[["System load","system_load","MW"],["RT price","spp_rt","$/MWh"],["Wind output","fuel_mix_wind","MW"]],market_analyst:[["Real-time SPP","spp_rt","$/MWh"],["Day-ahead SPP","spp_da","$/MWh"],["RT window maximum","spp_rt","$/MWh"]],grid_operations:[["System load","system_load","MW"],["Operating reserves","operating_reserves","MW"],["Outages","outages","MW"]]};const names={general:"General intelligence",market_analyst:"Market analyst intelligence",grid_operations:"Grid operations & reliability"};text($("#role-heading"),names[state.persona]);sets[state.persona].forEach(([label,key,unit],i)=>{const summary=intel.kpis?.[key]||{};node.append(metricCard(label,i===2&&state.persona==="market_analyst"?{...summary,current:summary.max}:summary,unit))});}
function renderFuel(fuels){const node=$("#fuel-grid");clear(node);const names={fuel_mix_wind:"Wind",fuel_mix_solar:"Solar",fuel_mix_battery_storage:"Battery storage"};Object.entries(names).forEach(([key,name])=>{const fuel=fuels[key]||{summary:{},points:[]},card=el("article","fuel-card");const head=el("div");head.append(el("h3","",name),el("div","metric-value",fmt(fuel.summary.current,"MW")));const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("class","chart");drawChart(svg,fuel.points,`${name} over selected window`);const stats=el("div","fuel-stats");[["Average",fuel.summary.average],["Minimum",fuel.summary.min],["Maximum",fuel.summary.max],["Coverage",fuel.summary.coverage]].forEach(([l,v])=>{const s=el("span","",l);s.append(el("b","",l==="Coverage"?`${safeText(v,0)} points`:fmt(v,"MW")));stats.append(s)});const expand=el("button","","Expand / inspect");expand.type="button";expand.addEventListener("click",()=>{stateLab(key,state.hours);$("#lab").scrollIntoView();});card.append(head,svg,stats,expand);node.append(card)});}
function renderReliability(intel){const rel=$("#reliability");clear(rel);const grid=el("div","reliability-grid");[["Reserves",intel.operations?.reserves,"MW"],["Outages",intel.operations?.outages,"MW"],["System frequency",intel.kpis?.frequency,"Hz"],["Battery output",intel.kpis?.fuel_mix_battery_storage,"MW"]].forEach(([l,s,u])=>grid.append(metricCard(l,s||{},u)));rel.append(grid);const risks=$("#risks");clear(risks);(intel.risks||[]).forEach(r=>{const item=el("article","risk-item");item.append(el("strong","",`${safeText(r.severity,"Notice")} · ${safeText(r.title,"Reliability notice")}`),el("p","",r.impact),el("small","",`${safeText(r.area,"ERCOT")} · ${marketTime(r.effective_at)} to ${marketTime(r.expires_at)}`));risks.append(item)});if(!risks.children.length)risks.append(el("p","empty","No active structured risk clusters are reported."));const market=$("#market");clear(market);const list=el("div","regional-list");(intel.market?.regional_prices||[]).slice(-12).forEach(p=>{const card=el("div","region");card.append(el("span","metric-label",p.location),el("div","metric-value",fmt(p.value,p.unit)),el("small","",marketTime(p.ts)));list.append(card)});market.append(list.children.length?list:el("p","empty","No regional price observations are available."));}

async function loadDesk(){try{const data=await api("/api/daily-use"),node=$("#priorities");clear(node);(data.priorities||[]).forEach((p,i)=>{const card=el("article","priority");card.append(el("span","metric-label",`Priority ${i+1} · ${safeText(p.severity)}`),el("h3","",p.title),el("p","",p.detail));node.append(card)});if(!node.children.length)node.append(el("p","empty","No decision priorities are available."));renderSimpleList($("#anomalies"),data.anomalies,"No significant anomalies reported.");renderSimpleList($("#calendar"),data.calendar,"No upcoming operating events reported.");text($("#desk-asof"),`Updated ${marketTime(new Date().toISOString())}`);}catch(e){errorState($("#priorities"),e)}}
function renderSimpleList(node,items,empty){clear(node);(items||[]).forEach(item=>node.append(el("p","",safeText(item))));if(!node.children.length)node.append(el("p","empty",empty));}

const citationPattern=/\[(?:cite:([^\]]+)|calc:([^\]]+))\]/g;
function paragraphWithEvidence(claim,sources){const p=el("p"),matches=[...safeText(claim,"").matchAll(citationPattern)],clean=safeText(claim,"").replace(citationPattern,"").trim();p.append(document.createTextNode(safeText(clean)));if(matches.length){const btn=el("button","evidence-button",`Evidence ${matches.length}`);btn.addEventListener("click",()=>openEvidence(matches,sources));p.append(btn)}return p;}
function openEvidence(matches,sources){const content=$("#evidence-content");clear(content);matches.forEach(match=>{const id=match[1]||match[2],source=(sources||[]).find(s=>String(s.document_id)===id||`obs-${s.observation_id}`===id)||{};const card=el("article","source-card");card.append(el("strong","",source.publisher||source.title||source.metric||`Evidence ${id}`),el("p","",source.title||`${safeText(source.metric,"Structured observation")} · ${safeText(source.settlement_point||source.location,"ERCOT")} · ${fmt(source.value,source.unit)}`),el("small","",marketTime(source.published_at||source.ts)));content.append(card)});$("#evidence-dialog").showModal();}
async function loadEdition(){try{const [edition,archive]=await Promise.all([api(`/api/edition/latest?role=${state.persona}`),api("/api/editions?limit=8")]);state.edition=edition;const node=$("#edition");clear(node);node.append(el("p","eyebrow",`${safeText(edition.role).replaceAll("_"," ")} · ${marketTime(edition.data_as_of)}`));const sources=[...(edition.sources||[]),...(edition.structured_sources||[])];(edition.sections||[]).forEach(section=>{node.append(el("h3","",section.title));(section.claims||[]).forEach(c=>node.append(paragraphWithEvidence(c,sources)))});if(!(edition.sections||[]).length)node.append(el("p","empty","This edition has no published sections."));const q=$("#quality");clear(q);[["Citation coverage",edition.quality?.citation_coverage??1],["Groundedness",edition.quality?.groundedness??1]].forEach(([l,v])=>{q.append(el("span","",`${l} · ${Math.round(Number(v)*100)}%`));const meter=el("div","quality-meter"),bar=el("span");bar.style.width=`${Math.max(0,Math.min(100,Number(v)*100))}%`;meter.append(bar);q.append(meter)});const a=$("#archive");clear(a);(archive.editions||[]).forEach(item=>a.append(el("button","",`${marketTime(item.generated_at)} · ${safeText(item.role).replaceAll("_"," ")}`)));}catch(e){errorState($("#edition"),e)}}

function stateLab(metric,hours){$("#lab-metric").value=metric;$("#lab-hours").value=String(hours);loadLab()}
async function loadLab(){const metric=$("#lab-metric").value,hours=$("#lab-hours").value,location=$("#lab-location").value.trim();const qs=new URLSearchParams({metric,hours});if(location)qs.set("location",location);$("#csv-link").href=`/api/data/export.csv?${qs}`;try{const data=await api(`/api/data/series?${qs}`),summary=$("#lab-summary");clear(summary);[["Current",data.summary?.current],["Average",data.summary?.average],["Minimum",data.summary?.min],["Maximum",data.summary?.max]].forEach(([l,v])=>summary.append(metricCard(l,{current:v},data.points?.[0]?.unit||"")));drawChart($("#lab-chart"),data.points,`${metric} detailed series`);const tbody=$("#lab-table");clear(tbody);(data.points||[]).slice(-500).reverse().forEach(p=>{const row=document.createElement("tr");[marketTime(p.ts),p.location,fmt(p.value,p.unit),`Source ${safeText(p.source_id)}`].forEach(v=>row.append(el("td","",v)));tbody.append(row)});if(!tbody.children.length){const row=document.createElement("tr"),cell=el("td","","No observations match this query.");cell.colSpan=4;row.append(cell);tbody.append(row)}}catch(e){errorState($("#lab-summary"),e)}}

function message(role,content,sources=[]){const node=el("div",role==="user"?"user-message":"assistant-message");node.append(document.createTextNode(safeText(content,"No readable answer was returned.")));if(sources.length){const btn=el("button","evidence-button",`Evidence ${sources.length}`);btn.addEventListener("click",()=>openEvidence(sources.map((_,i)=>["",String(i+1),""]),sources.map((s,i)=>({...s,document_id:i+1}))));node.append(btn)}$("#ask-thread").append(node);$("#ask-thread").scrollTop=$("#ask-thread").scrollHeight;return node;}
async function ask(question){message("user",question);state.history.push({role:"user",content:question});const pending=message("assistant","Checking structured data and cited evidence…");try{const result=await api("/api/ask",{method:"POST",body:JSON.stringify({question,role:state.persona,history:state.history.slice(-6)})});pending.remove();message("assistant",result.answer,Object.values(result.sources||{}));state.history.push({role:"assistant",content:safeText(result.answer)});state.history=state.history.slice(-6);localStorage.setItem("gridbrief.askHistory",JSON.stringify(state.history));if(result.chart_metric){$("#lab-metric").value=result.chart_metric;}}catch(e){pending.remove();message("assistant",safeText(e,"Ask AI is temporarily unavailable."));}}

function wire(){$("#persona").value=state.persona;$("#persona").addEventListener("change",e=>{state.persona=e.target.value;localStorage.setItem("gridbrief.persona",state.persona);text($("#persona-note"),{general:"A balanced view of system conditions, market movement, and risk.",market_analyst:"Prices, spreads, generation, and regional market context.",grid_operations:"Reliability, reserves, outages, and operating risk."}[state.persona]);renderIntelligence(state.intelligence||{kpis:{}});loadEdition()});$$("[data-hours]").forEach(button=>button.addEventListener("click",()=>{state.hours=Number(button.dataset.hours);$$("[data-hours]").forEach(b=>b.classList.toggle("active",b===button));state.cache.clear();loadWindow()}));$("#save-threshold").addEventListener("click",()=>{localStorage.setItem("gridbrief.priceThreshold",$("#price-threshold").value);text($("#threshold-status"),"Saved on this browser.")});$("#price-threshold").value=localStorage.getItem("gridbrief.priceThreshold")||"500";$("#wallboard").addEventListener("click",()=>document.body.classList.toggle("wallboard"));$("#lab-form").addEventListener("submit",e=>{e.preventDefault();loadLab()});$("#save-view").addEventListener("click",()=>localStorage.setItem("gridbrief.labView",JSON.stringify({metric:$("#lab-metric").value,hours:$("#lab-hours").value,location:$("#lab-location").value})));$("#ask-launch").addEventListener("click",()=>{$("#ask-panel").hidden=false;$("#ask-launch").setAttribute("aria-expanded","true");$("#ask-input").focus()});$("#ask-close").addEventListener("click",()=>{$("#ask-panel").hidden=true;$("#ask-launch").setAttribute("aria-expanded","false")});$("#ask-form").addEventListener("submit",e=>{e.preventDefault();const q=$("#ask-input").value.trim();if(q){$("#ask-input").value="";ask(q)}});$$("#suggestions button").forEach(b=>b.addEventListener("click",()=>ask(b.textContent)));$("#evidence-close").addEventListener("click",()=>$("#evidence-dialog").close());$("#print-edition").addEventListener("click",()=>window.print());$("#export-edition").addEventListener("click",()=>{if(!state.edition)return;const blob=new Blob([`<!doctype html><meta charset="utf-8"><title>GridBrief Edition</title>${$("#edition").outerHTML}`],{type:"text/html"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="gridbrief-edition.html";a.click();URL.revokeObjectURL(a.href)});try{const saved=JSON.parse(localStorage.getItem("gridbrief.labView"));if(saved){$("#lab-metric").value=saved.metric;$("#lab-hours").value=saved.hours;$("#lab-location").value=safeText(saved.location,"")}}catch{} }

document.addEventListener("DOMContentLoaded",async()=>{wire();await loadStatus();await loadWindow();await loadDesk();await loadEdition();await loadLab();});
